apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kkr9q0c8x-java-quarkus
  janus-idp.io/tekton: kkr9q0c8x-java-quarkus
  backstage.io/kubernetes-id: kkr9q0c8x-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kkr9q0c8x-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
